server:
  image: roccopetruzzi/pulsebs:latest_server
  ports:
    - 80:80
client:
  image: roccopetruzzi/pulsebs:latest_client
  ports:
    - 3000:3000
  links:
    - server
  stdin_open: true
  environment:
    - CHOKIDAR_USEPOLLING=true
mailer:
  image: roccopetruzzi/pulsebs:latest_mailer
  links:
    - server
